// <auto-generated />
using System;
using EduCompass.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduCompass.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230927210438_fixed-error")]
    partial class fixederror
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EduCompass.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Answer2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Answer3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Answer4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer1 = "Σωστό",
                            Answer2 = "Λάθος",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "Σωστό",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Answer1 = "Να δημιουργούν τάξεις, διεπαφές και αντικείμενα",
                            Answer2 = "Να γνωρίζουν τις βασικές αρχές της γλώσσας C#",
                            Answer3 = "Να μπορούν να αξιοποιήσουν τις βασικές αλγοριθμικές δομές σε γλώσσα C++",
                            Answer4 = "Να μπορούν να υλοποιούν προγραμματισμό sockets (TCP sockets και UDP sockets).",
                            CorrectAnswer = "Να δημιουργούν τάξεις, διεπαφές και αντικείμενα",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 3,
                            Answer1 = "Να μπορούν να σχεδιάζουν και να υλοποιούν αλγόριθμους για την αποτελεσματική κατασκευή συνδυαστικών αντικειμένων.",
                            Answer2 = "Να αναγνωρίζουν και να κατανοούν σύγχρονες τεχνικές σχεδίασης ολοκληρωμένων εφαρμογών λογισμικού με υπηρεσίες.",
                            Answer3 = "Να εντοπίζουν, αξιολογούν και αξιοποιούν λογισμικό που υλοποιείται σύμφωνα με τις βασικές αρχές της αντικειμενοστρεφούς σχεδίασης.",
                            Answer4 = "Να σχεδιάζουν αρχιτεκτονικά σχέδια λογισμικού βασισμένα σε γλώσσες μοντελοποίησης και διαγράμματα.",
                            CorrectAnswer = "Να εντοπίζουν, αξιολογούν και αξιοποιούν λογισμικό που υλοποιείται σύμφωνα με τις βασικές αρχές της αντικειμενοστρεφούς σχεδίασης.",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 4,
                            Answer1 = "Σωστό",
                            Answer2 = "Λάθος",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "Λάθος",
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 5,
                            Answer1 = "Java",
                            Answer2 = "",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "Java",
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 6,
                            Answer1 = "Ανάγνωση",
                            Answer2 = "",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "Ανάγνωση",
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 7,
                            Answer1 = "Σωστό",
                            Answer2 = "Λάθος",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "Σωστό",
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 8,
                            Answer1 = "Σωστό",
                            Answer2 = "Λάθος",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "Λάθος",
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 9,
                            Answer1 = "Εξαιρέσεις",
                            Answer2 = "",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "Εξαιρέσεις",
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 10,
                            Answer1 = "Αυτόνομη εργασία",
                            Answer2 = "Αρχιτεκτονική Πελάτη-Εξυπηρετητή (Client-Server)",
                            Answer3 = "Προσαρμογή σε νέες καταστάσεις",
                            Answer4 = "Σχεδιασμός και διαχείριση έργων",
                            CorrectAnswer = "Αρχιτεκτονική Πελάτη-Εξυπηρετητή (Client-Server)",
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 11,
                            Answer1 = "Σωστό",
                            Answer2 = "Λάθος",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "Σωστό",
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 12,
                            Answer1 = "γραφικά",
                            Answer2 = "",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "γραφικά",
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 13,
                            Answer1 = "ευφυών",
                            Answer2 = "",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "ευφυών",
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 14,
                            Answer1 = "Υφή επιφάνειας αντικειμένων. Διαχείριση πηγών φωτός, ήχων, κάμερας. Animations.",
                            Answer2 = "Ανάπτυξη εφαρμογών εικονικής πραγματικότητας στην πλατφόρμα Unity3D.",
                            Answer3 = "Κόσμοι τρισδιάστατων γραφικών. Τρισδιάστατα μοντέλα αντικειμένων.",
                            Answer4 = "Δομή και λειτουργία ενός ηλεκτρονικού παιχνιδιού.",
                            CorrectAnswer = "Δομή και λειτουργία ενός ηλεκτρονικού παιχνιδιού.",
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 15,
                            Answer1 = "Σωστό",
                            Answer2 = "Λάθος",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "Λάθος",
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 16,
                            Answer1 = "Unity3D",
                            Answer2 = "",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "Unity3D",
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 17,
                            Answer1 = "Σωστό",
                            Answer2 = "Λάθος",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "Σωστό",
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 18,
                            Answer1 = "συνιστώσες",
                            Answer2 = "",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "συνιστώσες",
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 19,
                            Answer1 = "Μετρήσεις Αντικειμένου Εικόνας",
                            Answer2 = "Εισαγωγή στα Γραφικά με Υπολογιστές, συστήματα απεικόνισης, χρώμα, γεωμετρικά σχήματα, μετασχηματισμοί, κίνηση.",
                            Answer3 = "Δομή και την λειτουργία ενός ευφυούς πράκτορα μέσα σε ένα περιβάλλον.",
                            Answer4 = "Αντιδρασιακοί πράκτορες (Reactive Agents) και Βουλητικοί πράκτορες (Deliberative Agents).",
                            CorrectAnswer = "Εισαγωγή στα Γραφικά με Υπολογιστές, συστήματα απεικόνισης, χρώμα, γεωμετρικά σχήματα, μετασχηματισμοί, κίνηση.",
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 20,
                            Answer1 = "VRML: sensors και animation, γενικές αρχές μοντελοποίησης σκελετού, πρότυπα μοντελοποίησης κίνησης σώματος (H-Anim, κ.ά.), scripting, ενσωμάτωση σε εφαρμογές, PROTOs, προτεινόμενες πρακτικές σχεδιασμού και ανάπτυξης.",
                            Answer2 = "VRML: σύνταξη, υλοποιήσεις, βασικά εργαλεία, γεωμετρία, μετασχηματισμοί, επαναχρησιμοποίηση κόμβων, εξωτερικές αναφορές, υλικά/χρώμα, φωτισμός, υφή, viewpoints, background, ήχος, κείμενο, billboards, HUDs.",
                            Answer3 = "Σχεδιασμός Κατανεμημένων Περιβαλλόντων Μάθησης.",
                            Answer4 = "Σχεδιασμός Κατανεμημένων Περιβαλλόντων Μάθησης.",
                            CorrectAnswer = "Σχεδιασμός Κατανεμημένων Περιβαλλόντων Μάθησης.",
                            QuestionId = 20
                        },
                        new
                        {
                            Id = 21,
                            Answer1 = "Να εφαρμόζουν πρακτικά τεχνολογίες ασφάλειας πληροφοριακών συστημάτων σε πραγματικές συνθήκες",
                            Answer2 = "Να αναλύει και να συγκρίνει μοντέλα ανάπτυξης λογισμικού",
                            Answer3 = "Να αναπτύσσει native mobile apps κάνοντας χρήση του Android SDK",
                            Answer4 = "Να χρησιμοποιεί πρακτικά τις πλέον σύγχρονες υπηρεσίες Cloud και Mobile backend as a service που παρέχει η Firebase",
                            CorrectAnswer = "Να εφαρμόζουν πρακτικά τεχνολογίες ασφάλειας πληροφοριακών συστημάτων σε πραγματικές συνθήκες",
                            QuestionId = 21
                        },
                        new
                        {
                            Id = 22,
                            Answer1 = "Android Studio",
                            Answer2 = "",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "Android Studio",
                            QuestionId = 22
                        },
                        new
                        {
                            Id = 23,
                            Answer1 = "Να σχεδιάζει και να αναπτύσσει εφαρμογές για κινητές και φορητές συσκευές υλοποιώντας τις πλέον σύγχρονες τεχνικές προγραμματισμού.",
                            Answer2 = "Να εκμεταλλεύεται τοπικές (SQLite) βάσεις δεδομένων.",
                            Answer3 = "Να επιλέγει μοντέλα ανάπτυξης λογισμικού ανάλογα με τις ανάγκες και να τα χρησιμοποιεί.",
                            Answer4 = "Να γνωρίζει τις τεχνικές σηματοδοσίας, διαχείρισης κινητικότητας και το πρωτόκολλο Mobile IP.",
                            CorrectAnswer = "Να γνωρίζει τις τεχνικές σηματοδοσίας, διαχείρισης κινητικότητας και το πρωτόκολλο Mobile IP.",
                            QuestionId = 23
                        },
                        new
                        {
                            Id = 24,
                            Answer1 = "Να διασφαλίζει την αποτελεσματικότητα των λογισμικών μέσω των προαναφερθέντων εφαρμογών.",
                            Answer2 = "Να αναγνωρίζει αρχές σχεδίασης λογισμικού με REST.",
                            Answer3 = "Να αξιοποιεί το εργαλείο Android Studio για την ανάπτυξη κινητών εφαρμογών.",
                            Answer4 = "Να γνωρίζει τις πλέον σύγχρονες υπηρεσίες Cloud και Mobile backend as a service που παρέχει η Firebase",
                            CorrectAnswer = "Να αναγνωρίζει αρχές σχεδίασης λογισμικού με REST.",
                            QuestionId = 24
                        },
                        new
                        {
                            Id = 25,
                            Answer1 = "Σωστό",
                            Answer2 = "Λάθος",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "Σωστό",
                            QuestionId = 25
                        },
                        new
                        {
                            Id = 26,
                            Answer1 = "Σωστό",
                            Answer2 = "Λάθος",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "Λάθος",
                            QuestionId = 26
                        },
                        new
                        {
                            Id = 27,
                            Answer1 = "Δομημένη",
                            Answer2 = "",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "Δομημένη",
                            QuestionId = 27
                        },
                        new
                        {
                            Id = 28,
                            Answer1 = "Scrum",
                            Answer2 = "Firebase",
                            Answer3 = "Rational Unified Process",
                            Answer4 = "DevOps",
                            CorrectAnswer = "Rational Unified Process",
                            QuestionId = 28
                        },
                        new
                        {
                            Id = 29,
                            Answer1 = "Σωστό",
                            Answer2 = "Λάθος",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "Σωστό",
                            QuestionId = 29
                        },
                        new
                        {
                            Id = 30,
                            Answer1 = "Cloud",
                            Answer2 = "",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "Cloud",
                            QuestionId = 30
                        },
                        new
                        {
                            Id = 31,
                            Answer1 = "Σωστό",
                            Answer2 = "Λάθος",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "Σωστό",
                            QuestionId = 31
                        },
                        new
                        {
                            Id = 32,
                            Answer1 = "αντιδρασιακός",
                            Answer2 = "",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "αντιδρασιακός",
                            QuestionId = 32
                        },
                        new
                        {
                            Id = 33,
                            Answer1 = "δομή",
                            Answer2 = "",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "δομή",
                            QuestionId = 33
                        },
                        new
                        {
                            Id = 34,
                            Answer1 = "Cleaning Agents",
                            Answer2 = "Radioactive Agents",
                            Answer3 = "Deliberative Agents",
                            Answer4 = "Federal Agents",
                            CorrectAnswer = "Deliberative Agents",
                            QuestionId = 34
                        },
                        new
                        {
                            Id = 35,
                            Answer1 = "Σωστό",
                            Answer2 = "Λάθος",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "Σωστό",
                            QuestionId = 35
                        },
                        new
                        {
                            Id = 36,
                            Answer1 = "Unity3D",
                            Answer2 = "",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "Unity3D",
                            QuestionId = 36
                        },
                        new
                        {
                            Id = 37,
                            Answer1 = "Σωστό",
                            Answer2 = "Λάθος",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "Λάθος",
                            QuestionId = 37
                        },
                        new
                        {
                            Id = 38,
                            Answer1 = "ενεργώ",
                            Answer2 = "",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "ενεργώ",
                            QuestionId = 38
                        },
                        new
                        {
                            Id = 39,
                            Answer1 = "Maslow",
                            Answer2 = "Khafre",
                            Answer3 = "Djoser",
                            Answer4 = "Cheops",
                            CorrectAnswer = "Maslow",
                            QuestionId = 39
                        },
                        new
                        {
                            Id = 40,
                            Answer1 = "Reactive Agents",
                            Answer2 = "Deliberative Agents",
                            Answer3 = "Κανένα από τα δύο",
                            Answer4 = "Και τα δύο",
                            CorrectAnswer = "Και τα δύο",
                            QuestionId = 40
                        },
                        new
                        {
                            Id = 41,
                            Answer1 = "Σωστό",
                            Answer2 = "Λάθος",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "Σωστό",
                            QuestionId = 41
                        },
                        new
                        {
                            Id = 42,
                            Answer1 = "χαρακτηριστικά",
                            Answer2 = "",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "χαρακτηριστικά",
                            QuestionId = 42
                        },
                        new
                        {
                            Id = 43,
                            Answer1 = "υλοποίησης",
                            Answer2 = "",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "υλοποίησης",
                            QuestionId = 43
                        },
                        new
                        {
                            Id = 44,
                            Answer1 = "First Person",
                            Answer2 = "Educational",
                            Answer3 = "Role-playing",
                            Answer4 = "Fourth Person",
                            CorrectAnswer = "Fourth Person",
                            QuestionId = 44
                        },
                        new
                        {
                            Id = 45,
                            Answer1 = "Σωστό",
                            Answer2 = "Λάθος",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "Σωστό",
                            QuestionId = 45
                        },
                        new
                        {
                            Id = 46,
                            Answer1 = "Unity3D",
                            Answer2 = "",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "Unity3D",
                            QuestionId = 46
                        },
                        new
                        {
                            Id = 47,
                            Answer1 = "Σωστό",
                            Answer2 = "Λάθος",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "Λάθος",
                            QuestionId = 47
                        },
                        new
                        {
                            Id = 48,
                            Answer1 = "C",
                            Answer2 = "C++",
                            Answer3 = "PythonFmu",
                            Answer4 = "C#",
                            CorrectAnswer = "C#",
                            QuestionId = 48
                        },
                        new
                        {
                            Id = 49,
                            Answer1 = "3D μοντέλα",
                            Answer2 = "bolts",
                            Answer3 = "sprites",
                            Answer4 = "animations",
                            CorrectAnswer = "bolts",
                            QuestionId = 49
                        },
                        new
                        {
                            Id = 50,
                            Answer1 = "Παίκτες",
                            Answer2 = "Πράκτορες",
                            Answer3 = "Κανένα από τα δύο",
                            Answer4 = "Και τα δύο",
                            CorrectAnswer = "Και τα δύο",
                            QuestionId = 50
                        },
                        new
                        {
                            Id = 51,
                            Answer1 = "Σωστό",
                            Answer2 = "Λάθος",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "Σωστό",
                            QuestionId = 51
                        },
                        new
                        {
                            Id = 52,
                            Answer1 = "desktop",
                            Answer2 = "",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "desktop",
                            QuestionId = 52
                        },
                        new
                        {
                            Id = 53,
                            Answer1 = "Visual Studio Enterprise Edition",
                            Answer2 = "IntelliJ IDEA",
                            Answer3 = "Visual Studio Code",
                            Answer4 = "QtSpim",
                            CorrectAnswer = "Visual Studio Enterprise Edition",
                            QuestionId = 53
                        },
                        new
                        {
                            Id = 54,
                            Answer1 = "Σωστό",
                            Answer2 = "Λάθος",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "Σωστό",
                            QuestionId = 54
                        },
                        new
                        {
                            Id = 55,
                            Answer1 = "λογισμικού",
                            Answer2 = "",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "λογισμικού",
                            QuestionId = 55
                        },
                        new
                        {
                            Id = 56,
                            Answer1 = "IDEs",
                            Answer2 = "GUIs",
                            Answer3 = "GNUs",
                            Answer4 = "ICPs",
                            CorrectAnswer = "IDEs",
                            QuestionId = 56
                        },
                        new
                        {
                            Id = 57,
                            Answer1 = "Σωστό",
                            Answer2 = "Λάθος",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "Λάθος",
                            QuestionId = 57
                        },
                        new
                        {
                            Id = 58,
                            Answer1 = "αποσφαλμάτωση",
                            Answer2 = "",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "αποσφαλμάτωση",
                            QuestionId = 58
                        },
                        new
                        {
                            Id = 59,
                            Answer1 = "Να εντοπίζουν, αξιολογούν και αξιοποιούν λογισμικό που υλοποιείται σύμφωνα με τις βασικές αρχές της αντικειμενοστρεφούς σχεδίασης.",
                            Answer2 = "Να σχεδιάζουν αρχιτεκτονικά σχέδια λογισμικού βασισμένα σε γλώσσες μοντελοποίησης και διαγράμματα.",
                            Answer3 = "Να μαθαίνουν, να αξιολογούν και να εντοπίζουν λογισμικό υλοποιημένο με εργαλεία οπτικού προγραμματισμού.",
                            Answer4 = "Να αναγνωρίζουν και να κατανοούν σύγχρονες τεχνικές σχεδίασης ολοκληρωμένων εφαρμογών λογισμικού με υπηρεσίες.",
                            CorrectAnswer = "Να μαθαίνουν, να αξιολογούν και να εντοπίζουν λογισμικό υλοποιημένο με εργαλεία οπτικού προγραμματισμού.",
                            QuestionId = 59
                        },
                        new
                        {
                            Id = 60,
                            Answer1 = "αποδοτικό",
                            Answer2 = "",
                            Answer3 = "",
                            Answer4 = "",
                            CorrectAnswer = "αποδοτικό",
                            QuestionId = 60
                        });
                });

            modelBuilder.Entity("EduCompass.Models.Career", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CoefficientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameInGreek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("Careers");

                    b.HasData(
                        new
                        {
                            Name = "Software Developer",
                            CoefficientName = "SoftwareEngineering",
                            NameInGreek = "Προγραμματιστής Λογισμικού"
                        },
                        new
                        {
                            Name = "Full-Stack Developer",
                            CoefficientName = "SoftwareEngineering",
                            NameInGreek = "Προγραμματιστής Full-Stack"
                        },
                        new
                        {
                            Name = "DevOps Engineer",
                            CoefficientName = "SoftwareEngineering",
                            NameInGreek = "Μηχανικός DevOps"
                        },
                        new
                        {
                            Name = "Software Consultant",
                            CoefficientName = "SoftwareEngineering",
                            NameInGreek = "Σύμβουλος Λογισμικού"
                        },
                        new
                        {
                            Name = "Machine Learning Engineer",
                            CoefficientName = "AI_ML",
                            NameInGreek = "Μηχανικός Μηχανικής Μάθησης"
                        },
                        new
                        {
                            Name = "Data Scientist",
                            CoefficientName = "AI_ML",
                            NameInGreek = "Επιστήμονας Δεδομένων"
                        },
                        new
                        {
                            Name = "N.L.P. Engineer",
                            CoefficientName = "AI_ML",
                            NameInGreek = "Μηχανικός Επεξεργασίας Φυσικής Γλώσσας"
                        },
                        new
                        {
                            Name = "Robotics Engineer",
                            CoefficientName = "AI_ML",
                            NameInGreek = "Μηχανικός Ρομποτικής"
                        },
                        new
                        {
                            Name = "UI/UX Designer",
                            CoefficientName = "UI_UX",
                            NameInGreek = "Σχεδιαστής UI/UX"
                        },
                        new
                        {
                            Name = "Visual Designer",
                            CoefficientName = "UI_UX",
                            NameInGreek = "Οπτικός Σχεδιαστής"
                        },
                        new
                        {
                            Name = "Front-End Developer",
                            CoefficientName = "UI_UX",
                            NameInGreek = "Προγραμματιστής Front-End"
                        },
                        new
                        {
                            Name = "Accessibility Specialist",
                            CoefficientName = "UI_UX",
                            NameInGreek = "Ειδικός Προσβασιμότητας"
                        },
                        new
                        {
                            Name = "Games Programmer",
                            CoefficientName = "GameDev",
                            NameInGreek = "Προγραμματιστής Ηλεκτρονικών Παιχνιδιών"
                        },
                        new
                        {
                            Name = "Games Designer",
                            CoefficientName = "GameDev",
                            NameInGreek = "Σχεδιαστής Ηλεκτρονικών Παιχνιδιών"
                        },
                        new
                        {
                            Name = "Level Designer",
                            CoefficientName = "GameDev",
                            NameInGreek = "Σχεδιαστής Επιπέδων Ηλεκτρονικών Παιχνιδιών"
                        },
                        new
                        {
                            Name = "Mobile App Developer",
                            CoefficientName = "MobileAppDev",
                            NameInGreek = "Προγραμματιστής Εφαρμογών Κινητών Τηλεφώνων"
                        },
                        new
                        {
                            Name = "iOS Developer",
                            CoefficientName = "MobileAppDev",
                            NameInGreek = "Προγραμματιστής Εφαρμογών για iOS"
                        },
                        new
                        {
                            Name = "Android Developer",
                            CoefficientName = "MobileAppDev",
                            NameInGreek = "Προγραμματιστής Εφαρμογών για Android"
                        },
                        new
                        {
                            Name = "Mobile UI/UX Designer",
                            CoefficientName = "MobileAppDev",
                            NameInGreek = "Σχεδιαστής UI/UX για Εφαρμογές Κινητών Τηλεφώνων"
                        },
                        new
                        {
                            Name = "Big Data Engineer",
                            CoefficientName = "DatabaseEngineering",
                            NameInGreek = "Μηχανικός Δεδομένων Μεγάλου Όγκου"
                        },
                        new
                        {
                            Name = "Data Architect",
                            CoefficientName = "DatabaseEngineering",
                            NameInGreek = "Αρχιτέκτονας Δεδομένων"
                        },
                        new
                        {
                            Name = "Database Developer",
                            CoefficientName = "DatabaseEngineering",
                            NameInGreek = "Προγραμματιστής Βάσεων Δεδομένων"
                        },
                        new
                        {
                            Name = "Cloud Data Engineer",
                            CoefficientName = "DatabaseEngineering",
                            NameInGreek = "Μηχανικός Δεδομένων Υπολογιστικής Νέφους"
                        },
                        new
                        {
                            Name = "Network Administrator",
                            CoefficientName = "ComputerNetworks",
                            NameInGreek = "Διαχειριστής Δικτύων"
                        },
                        new
                        {
                            Name = "Network Engineer",
                            CoefficientName = "ComputerNetworks",
                            NameInGreek = "Μηχανικός Δικτύων"
                        },
                        new
                        {
                            Name = "Network Security Specialist",
                            CoefficientName = "ComputerNetworks",
                            NameInGreek = "Ειδικός Ασφάλειας Δικτύων"
                        },
                        new
                        {
                            Name = "Computer Vision Engineer",
                            CoefficientName = "ComputerVisionAndGraphics",
                            NameInGreek = "Μηχανικός Γραφικών Υπολογιστών"
                        },
                        new
                        {
                            Name = "Computer Graphics Programmer",
                            CoefficientName = "ComputerVisionAndGraphics",
                            NameInGreek = "Προγραμματιστής Γραφικών"
                        },
                        new
                        {
                            Name = "3D Artist/Animator",
                            CoefficientName = "ComputerVisionAndGraphics",
                            NameInGreek = "Σχεδιαστής Τρισδιάστατων Σχεδίων"
                        },
                        new
                        {
                            Name = "Virtual Reality Developer",
                            CoefficientName = "ComputerVisionAndGraphics",
                            NameInGreek = "Προγραμματιστής Εικονικής Πραγματικότητας"
                        },
                        new
                        {
                            Name = "Security Analyst",
                            CoefficientName = "Security",
                            NameInGreek = "Αναλυτής Ασφαλείας"
                        },
                        new
                        {
                            Name = "Penetration Tester",
                            CoefficientName = "Security",
                            NameInGreek = "Ελεγκτής Διείσδυσης"
                        },
                        new
                        {
                            Name = "Security Engineer",
                            CoefficientName = "Security",
                            NameInGreek = "Μηχανικός Ασφαλείας"
                        },
                        new
                        {
                            Name = "Incident Responder",
                            CoefficientName = "Security",
                            NameInGreek = "Ανταποκριτής Συμβάντων"
                        },
                        new
                        {
                            Name = "Back-End Developer",
                            CoefficientName = "WebDev",
                            NameInGreek = "Προγραμματιστής Back-End"
                        },
                        new
                        {
                            Name = "Web Designer",
                            CoefficientName = "WebDev",
                            NameInGreek = "Σχεδιαστής Ιστοσελίδων"
                        },
                        new
                        {
                            Name = "Web App Developer",
                            CoefficientName = "WebDev",
                            NameInGreek = "Προγραμματιστής Διαδικτυακών Εφαρμογών"
                        });
                });

            modelBuilder.Entity("EduCompass.Models.Coefficient", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NameInGreek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("Coefficients");

                    b.HasData(
                        new
                        {
                            Name = "SoftwareEngineering",
                            NameInGreek = "Τεχνολογία Λογισμικού"
                        },
                        new
                        {
                            Name = "AI_ML",
                            NameInGreek = "Τεχνητή Νοημοσύνη και Μηχανική Μάθηση"
                        },
                        new
                        {
                            Name = "UI_UX",
                            NameInGreek = "Αλληλεπίδραση Ανθρώπου-Υπολογιστή"
                        },
                        new
                        {
                            Name = "Security",
                            NameInGreek = "Ασφάλεια"
                        },
                        new
                        {
                            Name = "ComputerNetworks",
                            NameInGreek = "Δίκτυα Υπολογιστών"
                        },
                        new
                        {
                            Name = "ComputerVisionAndGraphics",
                            NameInGreek = "Ανάλυση Εικόνας και Γραφικών"
                        },
                        new
                        {
                            Name = "GameDev",
                            NameInGreek = "Ανάπτυξη Ηλεκτρονικών Παιχνιδιών"
                        },
                        new
                        {
                            Name = "DatabaseEngineering",
                            NameInGreek = "Ανάπτυξη Βάσεων Δεδομένων και Επιστήμη Δεδομένων"
                        },
                        new
                        {
                            Name = "WebDev",
                            NameInGreek = "Ανάπτυξη Διαδικτυακών Εφαρμογών"
                        },
                        new
                        {
                            Name = "MobileAppDev",
                            NameInGreek = "Ανάπτυξη Εφαρμογών Κινητών Τηλεφώνων"
                        });
                });

            modelBuilder.Entity("EduCompass.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<string>("UUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AudioFileName = "",
                            Content = "",
                            Description = "",
                            Name = "Σύγχρονα Θέματα Τεχνολογίας Λογισμικού",
                            Semester = 7,
                            UUID = "ΠΛΘΕΤΚΑΕ01"
                        },
                        new
                        {
                            Id = 2,
                            AudioFileName = "",
                            Content = "",
                            Description = "",
                            Name = "Αντικειμενοστρεφής Ανάπτυξη Εφαρμογών",
                            Semester = 3,
                            UUID = "ΠΛΠΛΗ37-3"
                        },
                        new
                        {
                            Id = 3,
                            AudioFileName = "",
                            Content = "",
                            Description = "",
                            Name = "Αντικειμενοστρεφής Προγραμματισμός",
                            Semester = 2,
                            UUID = "ΠΛΠΛΗ37-2"
                        },
                        new
                        {
                            Id = 4,
                            AudioFileName = "",
                            Content = "",
                            Description = "",
                            Name = "Εικονική Πραγματικότητα",
                            Semester = 7,
                            UUID = "ΠΛΕΙΚ03"
                        },
                        new
                        {
                            Id = 5,
                            AudioFileName = "",
                            Content = "",
                            Description = "",
                            Name = "Ευφυείς Πράκτορες",
                            Semester = 8,
                            UUID = "ΠΛΕΥΠΡ01"
                        },
                        new
                        {
                            Id = 6,
                            AudioFileName = "",
                            Content = "",
                            Description = "",
                            Name = "Τεχνολογίες Ανάπτυξης Ηλεκτρονικών Παιχνιδιών",
                            Semester = 7,
                            UUID = "ΠΛΤΑΗΠ01"
                        });
                });

            modelBuilder.Entity("EduCompass.Models.CourseHasCoefficient", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("CoefficientName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("CourseId", "CoefficientName");

                    b.ToTable("CourseHasCoefficients");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CoefficientName = "MobileAppDev",
                            Value = 10
                        },
                        new
                        {
                            CourseId = 1,
                            CoefficientName = "SoftwareEngineering",
                            Value = 10
                        },
                        new
                        {
                            CourseId = 1,
                            CoefficientName = "WebDev",
                            Value = 5
                        },
                        new
                        {
                            CourseId = 2,
                            CoefficientName = "SoftwareEngineering",
                            Value = 10
                        },
                        new
                        {
                            CourseId = 2,
                            CoefficientName = "WebDev",
                            Value = 4
                        },
                        new
                        {
                            CourseId = 2,
                            CoefficientName = "MobileAppDev",
                            Value = 3
                        },
                        new
                        {
                            CourseId = 2,
                            CoefficientName = "DatabaseEngineering",
                            Value = 1
                        },
                        new
                        {
                            CourseId = 2,
                            CoefficientName = "GameDev",
                            Value = 1
                        },
                        new
                        {
                            CourseId = 3,
                            CoefficientName = "SoftwareEngineering",
                            Value = 10
                        },
                        new
                        {
                            CourseId = 3,
                            CoefficientName = "MobileAppDev",
                            Value = 2
                        },
                        new
                        {
                            CourseId = 3,
                            CoefficientName = "WebDev",
                            Value = 1
                        },
                        new
                        {
                            CourseId = 4,
                            CoefficientName = "GameDev",
                            Value = 10
                        },
                        new
                        {
                            CourseId = 4,
                            CoefficientName = "ComputerVisionAndGraphics",
                            Value = 7
                        },
                        new
                        {
                            CourseId = 4,
                            CoefficientName = "AI_ML",
                            Value = 2
                        },
                        new
                        {
                            CourseId = 5,
                            CoefficientName = "AI_ML",
                            Value = 10
                        },
                        new
                        {
                            CourseId = 5,
                            CoefficientName = "GameDev",
                            Value = 8
                        },
                        new
                        {
                            CourseId = 6,
                            CoefficientName = "GameDev",
                            Value = 10
                        },
                        new
                        {
                            CourseId = 6,
                            CoefficientName = "SoftwareEngineering",
                            Value = 3
                        });
                });

            modelBuilder.Entity("EduCompass.Models.CourseQuizGrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("QuestionIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeFinished")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeStarted")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CourseQuizGrades");
                });

            modelBuilder.Entity("EduCompass.Models.Grade", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("FinalGrade")
                        .HasColumnType("int");

                    b.Property<int>("InterestScore")
                        .HasColumnType("int");

                    b.HasKey("UserId", "CourseId");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("EduCompass.Models.PostGraduateInstitution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hyperlink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PostGraduateInstitutions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "Επιστήμη Δεδομένων και Μηχανική Μάθηση",
                            Description = "",
                            Hyperlink = "https://dsml.ece.ntua.gr/",
                            Name = "Εθνικό Μετσόβειο Πολυτεχνείο",
                            Town = "Αθήνα"
                        },
                        new
                        {
                            Id = 2,
                            Department = "Κυβερνοασφάλεια και Επιστήμη Δεδομένων",
                            Description = "",
                            Hyperlink = "https://www.cs.unipi.gr/index.php?option=com_k2&view=item&layout=item&id=609&Itemid=813&lang=el",
                            Name = "Πανεπιστήμιο Πειραιώς",
                            Town = "Πειραιάς"
                        },
                        new
                        {
                            Id = 3,
                            Department = "Προηγμένα Συστήματα Πληροφορικής - Ανάπτυξη Λογισμικού και Τεχνητής Νοημοσύνης",
                            Description = "",
                            Hyperlink = "https://www.cs.unipi.gr/index.php?option=com_k2&view=item&layout=item&id=626&Itemid=815&lang=el",
                            Name = "Πανεπιστήμιο Πειραιώς",
                            Town = "Πειραιάς"
                        },
                        new
                        {
                            Id = 4,
                            Department = "Ψηφιακός Πολιτισμός, Έξυπνες Πόλεις, IoT και Προηγμένες Ψηφιακές Τεχνολογίες",
                            Description = "",
                            Hyperlink = "https://www.cs.unipi.gr/index.php?option=com_k2&view=item&layout=item&id=576&Itemid=814&lang=el",
                            Name = "Πανεπιστήμιο Πειραιώς",
                            Town = "Πειραιάς"
                        },
                        new
                        {
                            Id = 5,
                            Department = "Προηγμένες Τεχνολογίες Πληροφορικής και Υπηρεσίες",
                            Description = "",
                            Hyperlink = "https://www.cs.unipi.gr/index.php?option=com_k2&view=item&layout=item&id=653&Itemid=812&lang=el",
                            Name = "Πανεπιστήμιο Πειραιώς",
                            Town = "Πειραιάς"
                        },
                        new
                        {
                            Id = 6,
                            Department = "Ανάπτυξη και Ασφάλεια Πληροφοριακών Συστημάτων",
                            Description = "",
                            Hyperlink = "https://mscis.cs.aueb.gr/el/normal/home",
                            Name = "Οικονομικό Πανεπιστήμιο Αθηνών",
                            Town = "Αθήνα"
                        },
                        new
                        {
                            Id = 7,
                            Department = "Επιστήμη Δεδομένων",
                            Description = "",
                            Hyperlink = "https://www.dept.aueb.gr/el/cs/content/%CF%80%CE%BC%CF%83-%CF%83%CF%84%CE%B7%CE%BD-%CE%B5%CF%80%CE%B9%CF%83%CF%84%CE%AE%CE%BC%CE%B7-%CE%B4%CE%B5%CE%B4%CE%BF%CE%BC%CE%AD%CE%BD%CF%89%CE%BD",
                            Name = "Οικονομικό Πανεπιστήμιο Αθηνών",
                            Town = "Αθήνα"
                        },
                        new
                        {
                            Id = 8,
                            Department = "Μηχανική Υπολογιστών, Τηλεποικοινωνιών και Δικτύων",
                            Description = "",
                            Hyperlink = "https://www.di.uoa.gr/eng",
                            Name = "Εθνικό Καποδιστριακό Πανεπιστήμιο Αθηνών",
                            Town = "Αθήνα"
                        },
                        new
                        {
                            Id = 9,
                            Department = "Τεχνολογίες Πληροφορικής και Τηλεποικοινωνιών",
                            Description = "",
                            Hyperlink = "https://www.di.uoa.gr/ict",
                            Name = "Εθνικό Καποδιστριακό Πανεπιστήμιο Αθηνών",
                            Town = "Αθήνα"
                        },
                        new
                        {
                            Id = 10,
                            Department = "Data Science and Information Technologies",
                            Description = "",
                            Hyperlink = "https://dsit.di.uoa.gr/",
                            Name = "Εθνικό Καποδιστριακό Πανεπιστήμιο Αθηνών",
                            Town = "Αθήνα"
                        },
                        new
                        {
                            Id = 11,
                            Department = "Προηγμένη Τεχνολογία Λογισμικού",
                            Description = "",
                            Hyperlink = "https://mai.uom.gr/frontend/articles.php?cid=41&t=Proigmeni-Texnologia-Logismikou",
                            Name = "Πανεπιστήμιο Μακεδονίας",
                            Town = "Θεσσαλονίκη"
                        },
                        new
                        {
                            Id = 12,
                            Department = "Ανάπτυξη Ψηφιακών Παιχνιδιών και Πολυμεσικών Εφαρμογών",
                            Description = "",
                            Hyperlink = "https://gamedev.uowm.gr/",
                            Name = "Πανεπιστήμιο Μακεδονίας",
                            Town = "Θεσσαλονίκη"
                        },
                        new
                        {
                            Id = 13,
                            Department = "Ανάπτυξη Εφαρμογών Ιστού και Κινητών Συσκευών",
                            Description = "",
                            Hyperlink = "https://mai.uom.gr/frontend/articles.php?cid=159&t=Anaptuksi-Efarmogwn-Istou-kai-Kinitwn-Suskeuwn",
                            Name = "Πανεπιστήμιο Μακεδονίας",
                            Town = "Θεσσαλονίκη"
                        },
                        new
                        {
                            Id = 14,
                            Department = "Αλληλεπίδραση Ανθρώπου-Υπολογιστή",
                            Description = "",
                            Hyperlink = "https://hcimaster.upatras.gr/regulation/",
                            Name = "Πανεπιστήμιο Πατρών",
                            Town = "Πάτρα"
                        });
                });

            modelBuilder.Entity("EduCompass.Models.PostGraduateInstitutionHasCoefficient", b =>
                {
                    b.Property<int>("PostGraduateInstitutionId")
                        .HasColumnType("int");

                    b.Property<string>("CoefficientName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("HasCoefficient")
                        .HasColumnType("bit");

                    b.HasKey("PostGraduateInstitutionId", "CoefficientName");

                    b.ToTable("PostGraduateInstitutionHasCoefficients");

                    b.HasData(
                        new
                        {
                            PostGraduateInstitutionId = 1,
                            CoefficientName = "AI_ML",
                            HasCoefficient = true
                        },
                        new
                        {
                            PostGraduateInstitutionId = 2,
                            CoefficientName = "AI_ML",
                            HasCoefficient = true
                        },
                        new
                        {
                            PostGraduateInstitutionId = 3,
                            CoefficientName = "AI_ML",
                            HasCoefficient = true
                        },
                        new
                        {
                            PostGraduateInstitutionId = 7,
                            CoefficientName = "AI_ML",
                            HasCoefficient = true
                        },
                        new
                        {
                            PostGraduateInstitutionId = 9,
                            CoefficientName = "AI_ML",
                            HasCoefficient = true
                        },
                        new
                        {
                            PostGraduateInstitutionId = 10,
                            CoefficientName = "AI_ML",
                            HasCoefficient = true
                        },
                        new
                        {
                            PostGraduateInstitutionId = 3,
                            CoefficientName = "SoftwareEngineering",
                            HasCoefficient = true
                        },
                        new
                        {
                            PostGraduateInstitutionId = 11,
                            CoefficientName = "SoftwareEngineering",
                            HasCoefficient = true
                        },
                        new
                        {
                            PostGraduateInstitutionId = 1,
                            CoefficientName = "DatabaseEngineering",
                            HasCoefficient = true
                        },
                        new
                        {
                            PostGraduateInstitutionId = 2,
                            CoefficientName = "DatabaseEngineering",
                            HasCoefficient = true
                        },
                        new
                        {
                            PostGraduateInstitutionId = 7,
                            CoefficientName = "DatabaseEngineering",
                            HasCoefficient = true
                        },
                        new
                        {
                            PostGraduateInstitutionId = 10,
                            CoefficientName = "DatabaseEngineering",
                            HasCoefficient = true
                        },
                        new
                        {
                            PostGraduateInstitutionId = 2,
                            CoefficientName = "Security",
                            HasCoefficient = true
                        },
                        new
                        {
                            PostGraduateInstitutionId = 4,
                            CoefficientName = "Security",
                            HasCoefficient = true
                        },
                        new
                        {
                            PostGraduateInstitutionId = 5,
                            CoefficientName = "Security",
                            HasCoefficient = true
                        },
                        new
                        {
                            PostGraduateInstitutionId = 6,
                            CoefficientName = "Security",
                            HasCoefficient = true
                        },
                        new
                        {
                            PostGraduateInstitutionId = 4,
                            CoefficientName = "Networks",
                            HasCoefficient = true
                        },
                        new
                        {
                            PostGraduateInstitutionId = 5,
                            CoefficientName = "Networks",
                            HasCoefficient = true
                        },
                        new
                        {
                            PostGraduateInstitutionId = 8,
                            CoefficientName = "Networks",
                            HasCoefficient = true
                        },
                        new
                        {
                            PostGraduateInstitutionId = 9,
                            CoefficientName = "Networks",
                            HasCoefficient = true
                        },
                        new
                        {
                            PostGraduateInstitutionId = 4,
                            CoefficientName = "WebDev",
                            HasCoefficient = true
                        },
                        new
                        {
                            PostGraduateInstitutionId = 6,
                            CoefficientName = "WebDev",
                            HasCoefficient = true
                        },
                        new
                        {
                            PostGraduateInstitutionId = 9,
                            CoefficientName = "WebDev",
                            HasCoefficient = true
                        },
                        new
                        {
                            PostGraduateInstitutionId = 13,
                            CoefficientName = "WebDev",
                            HasCoefficient = true
                        },
                        new
                        {
                            PostGraduateInstitutionId = 13,
                            CoefficientName = "UI_UX",
                            HasCoefficient = true
                        },
                        new
                        {
                            PostGraduateInstitutionId = 14,
                            CoefficientName = "UI_UX",
                            HasCoefficient = true
                        },
                        new
                        {
                            PostGraduateInstitutionId = 12,
                            CoefficientName = "GameDev",
                            HasCoefficient = true
                        },
                        new
                        {
                            PostGraduateInstitutionId = 13,
                            CoefficientName = "MobileAppDev",
                            HasCoefficient = true
                        },
                        new
                        {
                            PostGraduateInstitutionId = 12,
                            CoefficientName = "ComputerVisionAndGraphics",
                            HasCoefficient = true
                        });
                });

            modelBuilder.Entity("EduCompass.Models.PrerequisiteCourse", b =>
                {
                    b.Property<int>("BaseCourseId")
                        .HasColumnType("int");

                    b.Property<int>("PrerequisiteCourseId")
                        .HasColumnType("int");

                    b.HasKey("BaseCourseId", "PrerequisiteCourseId");

                    b.ToTable("PrerequisiteCourses");
                });

            modelBuilder.Entity("EduCompass.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Ένα από τα αντικέιμενα του μαθήματος Αντικειμενοστρεφής Προγραμματισμός η ομαδική εργασία.",
                            CourseId = 3
                        },
                        new
                        {
                            Id = 2,
                            Content = "Ποιο από τα παρακάτω αποτελεί μαθησιακό αποτέλεσμα του μαθήματος Αντικειμενοστρεφής Προγραμματισμός;",
                            CourseId = 3
                        },
                        new
                        {
                            Id = 3,
                            Content = "Ποιο από τα παρακάτω αποτελεί μαθησιακό αποτέλεσμα του μαθήματος Αντικειμενοστρεφής Προγραμματισμός;",
                            CourseId = 3
                        },
                        new
                        {
                            Id = 4,
                            Content = "Παρακολουθώντας το μάθημα Αντικειμενοστρεφής Προγραμματισμός, οι φοιτητές είναι ικανοί να θα παράγουν εφαρμογές πελάτη-εξυπηρετητή.",
                            CourseId = 3
                        },
                        new
                        {
                            Id = 5,
                            Content = "Το κύριο αντικείμενο του μαθήματος Αντικειμενοστρεφής Προγραμματισμός  είναι η εισαγωγή στον αντικειμενοστρεφή προγραμματισμό με πλήρη ανάλυση της γλώσσας προγραμματισμού ______.",
                            CourseId = 3
                        },
                        new
                        {
                            Id = 6,
                            Content = "Στα πλαίσια του μαθήματος Αντικειμενοστρεφής Προγραμματισμός οι φοιτητές μαθαίνουν να χειρίζονται αρχεία προορισμένα για _________ και αποθήκευση δεδομένων.",
                            CourseId = 3
                        },
                        new
                        {
                            Id = 7,
                            Content = "Στα πλαίσια του μαθήματος Αντικειμενοστρεφής Προγραμματισμός οι φοιτητές μαθαίνουν την έννοια της κληρονομικότητας.",
                            CourseId = 3
                        },
                        new
                        {
                            Id = 8,
                            Content = "Παρακολουθώντας το μάθημα Αντικειμενοστρεφής Προγραμματισμός, οι φοιτητές είναι ικανοί  να παράγουν εφαρμογές με αποδοτικό και ταχύ ρυθμό.",
                            CourseId = 3
                        },
                        new
                        {
                            Id = 9,
                            Content = "Στα πλαίσια του μαθήματος Αντικειμενοστρεφής Προγραμματισμός οι φοιτητές μαθαίνουν να διαχειρίζονται αποτελεσματικά και με χρήση των κατάλληλων εργαλείων τις ________ που ανακύπτουν.",
                            CourseId = 3
                        },
                        new
                        {
                            Id = 10,
                            Content = "Ποιο από τα παρακάτω ΔΕΝ ανήκει στο αντικείμενο του μαθήματος Αντικειμενοστρεφής Προγραμματισμός;",
                            CourseId = 3
                        },
                        new
                        {
                            Id = 11,
                            Content = "Η Εικονική Πραγματικότητα είναι το επιστημονικό πεδίο με αντικείμενο την αναπαράσταση κόσμων με τη βοήθεια ηλεκτρονικών υπολογιστών.",
                            CourseId = 4
                        },
                        new
                        {
                            Id = 12,
                            Content = "Τα ______ με υπολογιστές διαδραματίζουν βασικό ρόλο στην Εικονική Πραγματικότητα.",
                            CourseId = 4
                        },
                        new
                        {
                            Id = 13,
                            Content = "Η Εικονική Πραγματικότητα, κυρίως μέσω των _______ Εικονικών Συστημάτων, έχει πλήθος εφαρμογών στην εκπαίδευση, την ψυχαγωγία, την προσομοίωση, την αλληλεπίδραση ανθρώπου – υπολογιστή και την επιστημονική έρευνα",
                            CourseId = 4
                        },
                        new
                        {
                            Id = 14,
                            Content = "Ποιο από τα παρακάτω ΔΕΝ αποτελεί αντικείμενο του μαθήματος Εικονική Πραγματικότητα;",
                            CourseId = 4
                        },
                        new
                        {
                            Id = 15,
                            Content = "Στόχος του μαθήματος Εικονική Πραγματικότητα είναι να αποκτήσουν οι φοιτητές γνώσεις και ικανότητες χρήσης/δημιουργίας μετρικών αξιολόγησης παιχνιδιών βάσει των στόχων που τέθηκαν κατά τη σχεδίασή τους.",
                            CourseId = 4
                        },
                        new
                        {
                            Id = 16,
                            Content = "Πως ονομάζεται το περιβάλλον με το οποίο θα εξοικιωθούν οι φοιτητές για την ανάπτηξη συστημάτων Εικονικής Πραγματικότητας;",
                            CourseId = 4
                        },
                        new
                        {
                            Id = 17,
                            Content = "Στόχος του μαθήματος Εικονική Πραγματικότητα είναι η εξοικείωση των φοιτητών με σύγχρονες τεχνολογίες, μεθόδους και εργαλεία για τη δημιουργία ολοκληρωμένων εφαρμογών Εικονικής Πραγματικότητας.",
                            CourseId = 4
                        },
                        new
                        {
                            Id = 18,
                            Content = "Μέσω της παρακολούθησης του μαθήματος Εικονική Πραγματικότητα ο φοιτητής γνωρίζει τις ________ ενός συστήματος Εικονικής Πραγματικότητας.",
                            CourseId = 4
                        },
                        new
                        {
                            Id = 19,
                            Content = "Ποιο από τα παρακάτω αποτελεί διδακτική ενότητα του μαθήματος Εικονική Πραγματικότητα;",
                            CourseId = 4
                        },
                        new
                        {
                            Id = 20,
                            Content = "Ποιο από τα παρακάτω ΔΕΝ αποτελεί διδακτική ενότητα του μαθήματος Εικονική Πραγματικότητα;",
                            CourseId = 4
                        },
                        new
                        {
                            Id = 21,
                            Content = "Ποιο από τα παρακάτω ΔΕΝ αποτελεί μαθησιακό αποτέλεσμα του μαθήματος Σύγχρονα Θέματα Τεχνολογίας Λογισμικού;",
                            CourseId = 1
                        },
                        new
                        {
                            Id = 22,
                            Content = "Η ανάπτυξη των mobile apps στο μάθημα Σύγχρονα Θέματα Τεχνολογίας Λογισμικού  υλοποιείται με τη χρήση του περιβάλλοντος ανάπτυξης λογισμικού ___________.",
                            CourseId = 1
                        },
                        new
                        {
                            Id = 23,
                            Content = "Ποιο από τα παρακάτω ΔΕΝ αποτελεί μαθησιακό αποτέλεσμα του μαθήματος Σύγχρονα Θέματα Τεχνολογίας Λογισμικού;",
                            CourseId = 1
                        },
                        new
                        {
                            Id = 24,
                            Content = "Ποιο από τα παρακάτω ΔΕΝ αποτελεί μαθησιακό αποτέλεσμα του μαθήματος Σύγχρονα Θέματα Τεχνολογίας Λογισμικού;",
                            CourseId = 1
                        },
                        new
                        {
                            Id = 25,
                            Content = "Tο μάθημα Σύγχρονα Θέματα Τεχνολογίας Λογισμικού καλύπτει και την ύλη που αφορά στους αισθητήρες των κινητών συσκευών, στις υπηρεσίες γεοεντοπισμού και σε πλήθος άλλων προχωρημένων τεχνικών προγραμματισμού.",
                            CourseId = 1
                        },
                        new
                        {
                            Id = 26,
                            Content = "Η ύλη του μαθήματος Σύγχρονα Θέματα Τεχνολογίας Λογισμικού περιλαμβάνει κυρίως τη χρήση της αντικειμενοστρεφούς γλώσσας προγραμματισμού C#.",
                            CourseId = 1
                        },
                        new
                        {
                            Id = 27,
                            Content = "Ένα από τα αντκείμενα του μαθήματος Σύγχρονα Θέματα Τεχνολογίας Λογισμικού είναι η “Ανάλυση απαιτήσεων: __________ Ανάλυση και Αντικειμενοστρεφής Ανάλυση”.",
                            CourseId = 1
                        },
                        new
                        {
                            Id = 28,
                            Content = "Ποιο από τα παρακάτω αποτελεί μοντέλο ανάπτυξης λογισμικού που αναλύεται στα πλαίσια του μαθήματος Σύγχρονα Θέματα Τεχνολογίας Λογισμικού;",
                            CourseId = 1
                        },
                        new
                        {
                            Id = 29,
                            Content = "Ένα από τα αντικέιμενα του μαθήματος Σύγχρονα Θέματα Τεχνολογίας Λογισμικού είναι προϋπολογισμός κόστους λογισμικού.",
                            CourseId = 1
                        },
                        new
                        {
                            Id = 30,
                            Content = "Παρακολουθώντας το μάθημα Σύγχρονα Θέματα Τεχνολογίας Λογισμικού, μπορεί κανείς να χρησιμοποιεί πρακτικά τις πλέον σύγχρονες υπηρεσίες ______ και Mobile backend as a service που παρέχει η Firebase.",
                            CourseId = 1
                        },
                        new
                        {
                            Id = 31,
                            Content = "Μετά την ολοκλήρωση της παρακολούθησης του μαθήματος Ευφυείς Πράκτορες ο φοιτητής μπορεί να εφαρμόζει τα μοντέλα “αντιλαμβάνομαι-αποφασίζω-ενεργώ” (Sense-Decide-Act), BDI (Belief-Desire-Intention), σε διάφορες περιπτώσεις πρακτόρων.",
                            CourseId = 5
                        },
                        new
                        {
                            Id = 32,
                            Content = "Μετά την ολοκλήρωση της παρακολούθησης του μαθήματος Ευφυείς Πράκτορες ο φοιτητής διακρίνει και εκτιμά πότε είναι απαραίτητος ένας _________ πράκτορας και πότε βουλητικός πράκτορας.",
                            CourseId = 5
                        },
                        new
                        {
                            Id = 33,
                            Content = "Μετά την ολοκλήρωση της παρακολούθησης του μαθήματος Ευφυείς Πράκτορες ο φοιτητής κατανοεί την ____ ενός ευφυούς πράκτορα",
                            CourseId = 5
                        },
                        new
                        {
                            Id = 34,
                            Content = "Ποίο από τα παρακάτω αποτελεί είδος ευφυούς πράκτορα που μελετάται στο μάθυμα Ευφυείς Πράκτορες;",
                            CourseId = 5
                        },
                        new
                        {
                            Id = 35,
                            Content = "Μετά την ολοκλήρωση της παρακολούθησης του μαθήματος Ευφυείς Πράκτορες  ο φοιτητής  αναπτύσσει αλγορίθμους για εύρεση μονοπατιού (path finding), και σχεδιασμό ενεργειών (plan generation)",
                            CourseId = 5
                        },
                        new
                        {
                            Id = 36,
                            Content = "Πως ονομάζεται το περιβάλλον με το οποίο θα εξοικιωθούν οι φοιτητές για την ανάπτηξη εφαρμογών ευφυή πρακτόρων;",
                            CourseId = 5
                        },
                        new
                        {
                            Id = 37,
                            Content = "Η συναισθηματική διαλεκτική σε ευφυείς πράκτορες αποτελεί αντικείμενο του μαθήματος Ευφυείς Πράκτορες.",
                            CourseId = 5
                        },
                        new
                        {
                            Id = 38,
                            Content = "Μέσω της παρακολούθησης του μαθήματος Ευφυείς Πράκτορες ο φοιτητής μαθαίνει να εφαρμόζει το μοντέλο “αντιλαμβάνομαι-αποφασίζω-________”",
                            CourseId = 5
                        },
                        new
                        {
                            Id = 39,
                            Content = "Αντικείμενο του μαθήματος Ευφυείς Πράκτορες είναι  ο σχεδιασμός ενεργειών, βασισμένος σε κίνητρα και η πυραμίδα του ________.",
                            CourseId = 5
                        },
                        new
                        {
                            Id = 40,
                            Content = "Mε ποιο είδος πρακτόρων θα ασχοληθούν οι φοιτητές στα πλαίσια του μαθληματος Ευφυείς Πράκτορες;",
                            CourseId = 5
                        },
                        new
                        {
                            Id = 41,
                            Content = "Παρακολουθώντας το μάθημα Τεχνολογίες Ανάπτυξης Ηλεκτρονικών Παιχνιδιών, οι φοιτητές θα μπορούν να αναπτύσουν εφαρμογές ηλεκτρονικών παιχνιδιών στο περιβάλλον της Python.",
                            CourseId = 6
                        },
                        new
                        {
                            Id = 42,
                            Content = "Στόχος του μαθήματος Τεχνολογίες Ανάπτυξης Ηλεκτρονικών Παιχνιδιών είναι να αποκτήσουν οι φοιτητές βασικές γνώσεις για τον ρόλο, τους τύπους και τα ________ των παιχνιδιών, καθώς και για τη συνολική διαδικασία δημιουργίας ενός παιχνιδιού.",
                            CourseId = 6
                        },
                        new
                        {
                            Id = 43,
                            Content = "Στόχος του μαθήματος Τεχνολογίες Ανάπτυξης Ηλεκτρονικών Παιχνιδιών είναι να αποκτήσουν οι φοιτητές ικανότητες σχεδίασης και _________ παιχνιδιών αξιοποιώντας σύγχρονα εργαλεία, διασυνδέσεις και γλώσσες προγραμματισμού,",
                            CourseId = 6
                        },
                        new
                        {
                            Id = 44,
                            Content = "Ποιο από τα παρακάτω ΔΕΝ αποτελεί κατηγορία ηλεκτρονικών παιχνιδιών;",
                            CourseId = 6
                        },
                        new
                        {
                            Id = 45,
                            Content = "Στόχος του μαθήματος Τεχνολογίες Ανάπτυξης Ηλεκτρονικών Παιχνιδιών είναι να αποκτήσουν οι φοιτητές γνώσεις και ικανότητες χρήσης/δημιουργίας μετρικών αξιολόγησης παιχνιδιών βάσει των στόχων που τέθηκαν κατά τη σχεδίασή τους.",
                            CourseId = 6
                        },
                        new
                        {
                            Id = 46,
                            Content = "Στα πλάισια του μαθήαμτος Τεχνολογίες Ανάπτυξης Ηλεκτρονικών Παιχνιδιών ο φοιτητής μαθαίνει να συνοψίζει τις απαιτούμενες γνώσεις σχετικά με την ανάπτυξη ηλεκτρονικών παιχνιδιών στο περιβάλλον της ________",
                            CourseId = 6
                        },
                        new
                        {
                            Id = 47,
                            Content = "Στόχος του μαθήματος Τεχνολογίες Ανάπτυξης Ηλεκτρονικών Παιχνιδιών είναι η εξοικείωση των φοιτητών με σύγχρονες τεχνολογίες, μεθόδους και εργαλεία για τη δημιουργία ολοκληρωμένων διαδικτυακών εφαρμογών.",
                            CourseId = 6
                        },
                        new
                        {
                            Id = 48,
                            Content = "Το αντικείενο του μαθήματος Τεχνολογίες Ανάπτυξης Ηλεκτρονικών Παιχνιδιών περιλαμβάνει τη σχεδίαση ενός παιχνιδιού σε ________.",
                            CourseId = 6
                        },
                        new
                        {
                            Id = 49,
                            Content = "Ποιο από τα παρακάτω ΔΕΝ αποτελεί συστατικά ηλεκτρονικών παιχνιδιών στο Διαδίκτυο;",
                            CourseId = 6
                        },
                        new
                        {
                            Id = 50,
                            Content = "Ο κόσμος ενός ηλεκτρονικού αποτελείται από χαρακτήρες που μπορεί να είναι...;",
                            CourseId = 6
                        },
                        new
                        {
                            Id = 51,
                            Content = "Η ύλη του μαθήματος Αντικειμενοστρεφής Ανάπτυξη Εφαρμογών περιλαμβάνει κυρίως τη χρήση της αντικειμενοστρεφούς γλώσσας προγραμματισμού C#.",
                            CourseId = 2
                        },
                        new
                        {
                            Id = 52,
                            Content = "Μέσω του μαθήματος Αντικειμενοστρεφής Ανάπτυξη Εφαρμογών, οι φοιτητές μαθαίνουν να αναπτύσσουν _______, web, ή/και mobile εφαρμογές.",
                            CourseId = 2
                        },
                        new
                        {
                            Id = 53,
                            Content = "Ποιο εργαλείο ανάπτυξης εφαρμογών χρησιμοποιείται στα πλαίσια του μαθήματος Αντικειμενοστρεφής Ανάπτυξη Εφαρμογών;",
                            CourseId = 2
                        },
                        new
                        {
                            Id = 54,
                            Content = "Μέσω του μαθήματος Αντικειμενοστρεφής Ανάπτυξη Εφαρμογών, οι φοιτητές μαθαίνουν να αναπτύσσουν λογισμικό για ένα μεγάλο πλήθος από πεδία, συμπεριλαμβανομένων των παραθυρικών εφαρμογών, των εφαρμογών κονσόλας, των εφαρμογών web και των mobile εφαρμογών.",
                            CourseId = 2
                        },
                        new
                        {
                            Id = 55,
                            Content = "Μέσω του μαθήματος Αντικειμενοστρεφής Ανάπτυξη Εφαρμογών, οι φοιτητές εκτίθονται σε σύγχρονες τεχνικές προγραμματισμού με στόχο την ποιότητα του παραγόμενου _________, καθώς και την ταχύτητα ανάπτυξης σύνθετων και πολύπλοκων προγραμμάτων/έργων.",
                            CourseId = 2
                        },
                        new
                        {
                            Id = 56,
                            Content = "Στο πλαίσιο του μαθήματος Αντικειμενοστρεφής Ανάπτυξη Εφαρμογών δίνεται ιδιαίτερη έμφαση στα ολοκληρωμένα περιβάλλοντα ανάπτυξης τα οποία ονομάζονται και:",
                            CourseId = 2
                        },
                        new
                        {
                            Id = 57,
                            Content = "Μέσω του μαθήματος Αντικειμενοστρεφής Ανάπτυξη Εφαρμογών, οι φοιτητές μαθαίνουν να αναγνωρίζουν και να εξηγούν τι είναι γλώσσα και γραμματική και πώς συμβολίζονται.",
                            CourseId = 2
                        },
                        new
                        {
                            Id = 58,
                            Content = "Μέσω του μαθήματος Αντικειμενοστρεφής Ανάπτυξη Εφαρμογών, οι φοιτητές μαθάινουν να κάνουν ________ λογισμικού με τα πλέον σύγχρονα εργαλεία.",
                            CourseId = 2
                        },
                        new
                        {
                            Id = 59,
                            Content = "Ποιο από τα παρακάτω αποτελεί μαθησιακό αποτέλεσμα του μαθήματος Αντικειμενοστρεφής Ανάπτυξη Εφαρμογών;",
                            CourseId = 2
                        },
                        new
                        {
                            Id = 60,
                            Content = "Μέσω του μαθήματος Αντικειμενοστρεφής Ανάπτυξη Εφαρμογών , οι φοιτητές μαθάινουν να παράγουν εφαρμογές με _______ και ταχύ ρυθμό.",
                            CourseId = 2
                        });
                });

            modelBuilder.Entity("EduCompass.Models.TimeSpent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("TotalTime")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TimeSpents");
                });

            modelBuilder.Entity("EduCompass.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasCompletedIntroTest")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EduCompass.Models.UserHasCoefficient", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("CoefficientName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Percentage")
                        .HasColumnType("float");

                    b.HasKey("UserId", "CoefficientName");

                    b.ToTable("UserHasCoefficients");
                });
#pragma warning restore 612, 618
        }
    }
}
